"""empty message

Revision ID: ca947f39ec1f
Revises: 2a46aa56ae8f
Create Date: 2023-08-20 13:22:30.046711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca947f39ec1f'
down_revision = '2a46aa56ae8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ray', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(length=10000),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.Text(length=1000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('ray', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(length=10000),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###
